# Generated by Django 5.1.7 on 2025-03-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='date',
            field=models.DateField(),
        ),
    ]
